openapi: 3.0.0
info:
  title: Billing API
  description: API for managing orders and billing
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server for testing
tags:
  - name: Orders
    description: Operations related to orders

paths:
  /orders:
    post:
      summary: Create a new order
      tags: 
        - Orders
      requestBody:
        description: Order details that need to be created
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  example: 1
                number_of_items:
                  type: integer
                  example: 3
                total_amount:
                  type: number
                  format: float
                  example: 50.75
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  message:
                    type: string
        '400':
          description: Invalid input data
          
    get:
      summary: Get all orders
      tags: 
        - Orders
      responses:
        '200':
          description: A list of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    user_id:
                      type: integer
                    number_of_items:
                      type: integer
                    total_amount:
                      type: number
                      format: float
        '500':
          description: Server error

  /orders/{id}:
    get:
      summary: Get an order by ID
      tags: 
        - Orders
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the order to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: A single order
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  user_id:
                    type: integer
                  number_of_items:
                    type: integer
                  total_amount:
                    type: number
                    format: float
        '404':
          description: Order not found

    delete:
      summary: Delete an order by ID
      tags: 
        - Orders
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the order to delete
          schema:
            type: integer
      responses:
        '204':
          description: Order deleted successfully
        '404':
          description: Order not found

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
        user_id:
          type: integer
        number_of_items:
          type: integer
        total_amount:
          type: number
          format: float
